export const GET_GALLERY = 'GET_GALLERY';
export const GET_GALLERY_SUCCESS = 'GET_GALLERY_SUCCESS';
export const GET_GALLERY_FAILURE = 'GET_GALLERY_FAILURE';
export const SHIFT_GALLERY = 'SHIFT_GALLERY';
export const SHIFT_GALLERY_SUCCESS = 'SHIFT_GALLERY_SUCCESS';
